# Code generated by ipcgen. DO NOT EDIT.
"""Messages of package schedpolicy, from policy.ipc.

encode() returns the encoding. decode(buf) raises ValueError when buf is malformed.
The module needs only the standard library of CPython 3.8 or later.
"""

from __future__ import annotations

import dataclasses as _dc
import struct as _st
import typing as _t

_Error = ValueError


def _get_var(buf: memoryview, off: int) -> _t.Tuple[bytes, int]:
	if len(buf) - off < 4:
		raise _Error("schedpolicy: a length runs past the end of the input")
	(n,) = _st.unpack_from("<I", buf, off)
	off += 4
	if n > len(buf) - off:
		raise _Error("schedpolicy: a length runs past the end of the input")
	return bytes(buf[off:off + n]), off + n


def _put_var(out: bytearray, raw: bytes) -> None:
	if len(raw) > 0xFFFFFFFF:
		raise _Error("schedpolicy: a string or bytes field is longer than 4 GiB")
	out += _st.pack("<I", len(raw))
	out += raw


def _bool(b: int) -> bool:
	if b > 1:
		raise _Error("schedpolicy: a bool is neither 0 nor 1")
	return b == 1


def _str(raw: bytes) -> str:
	try:
		return raw.decode("utf-8")
	except UnicodeDecodeError:
		raise _Error("schedpolicy: a string is not valid UTF-8") from None


def _arr(v: _t.Sequence[_t.Any], n: int) -> _t.Sequence[_t.Any]:
	if len(v) != n:
		raise _Error("schedpolicy: an array holds %d items, want %d" % (len(v), n))
	return v


def _view(buf: _t.Any) -> memoryview:
	return memoryview(buf).cast("B")


@_dc.dataclass
class Hello:
	TYPE_ID = 1
	FIXED_SIZE = 12

	protocol: int = 0
	rank: int = 0
	world: int = 0

	def encode(self) -> bytes:
		buf = bytearray(12)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: Hello: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> Hello:
		buf = _view(buf)
		if len(buf) < 12:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 12
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<I", buf, off + 0, self.protocol)
		_st.pack_into("<I", buf, off + 4, self.rank)
		_st.pack_into("<I", buf, off + 8, self.world)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> Hello:
		return cls(
			protocol=_st.unpack_from("<I", buf, off + 0)[0],
			rank=_st.unpack_from("<I", buf, off + 4)[0],
			world=_st.unpack_from("<I", buf, off + 8)[0],
		)


@_dc.dataclass
class Init:
	TYPE_ID = 2
	FIXED_SIZE = 32

	burst_tokens: int = 0
	device_tokens: int = 0
	host_tokens: int = 0
	throttle: bool = False

	def encode(self) -> bytes:
		buf = bytearray(32)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: Init: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> Init:
		buf = _view(buf)
		if len(buf) < 32:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 32
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<q", buf, off + 0, self.burst_tokens)
		_st.pack_into("<q", buf, off + 8, self.device_tokens)
		_st.pack_into("<q", buf, off + 16, self.host_tokens)
		buf[off + 24] = 1 if self.throttle else 0

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> Init:
		return cls(
			burst_tokens=_st.unpack_from("<q", buf, off + 0)[0],
			device_tokens=_st.unpack_from("<q", buf, off + 8)[0],
			host_tokens=_st.unpack_from("<q", buf, off + 16)[0],
			throttle=_bool(buf[off + 24]),
		)


@_dc.dataclass
class ShouldDeferPrefill:
	TYPE_ID = 3
	FIXED_SIZE = 3

	prefill_pending: bool = False
	decode_runnable: bool = False
	continues_chunk: bool = False

	def encode(self) -> bytes:
		buf = bytearray(3)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: ShouldDeferPrefill: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> ShouldDeferPrefill:
		buf = _view(buf)
		if len(buf) < 3:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 3
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		buf[off + 0] = 1 if self.prefill_pending else 0
		buf[off + 1] = 1 if self.decode_runnable else 0
		buf[off + 2] = 1 if self.continues_chunk else 0

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> ShouldDeferPrefill:
		return cls(
			prefill_pending=_bool(buf[off + 0]),
			decode_runnable=_bool(buf[off + 1]),
			continues_chunk=_bool(buf[off + 2]),
		)


@_dc.dataclass
class PrefillTokenBudget:
	TYPE_ID = 4
	FIXED_SIZE = 1

	continues_chunk: bool = False

	def encode(self) -> bytes:
		buf = bytearray(1)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: PrefillTokenBudget: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> PrefillTokenBudget:
		buf = _view(buf)
		if len(buf) < 1:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 1
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		buf[off + 0] = 1 if self.continues_chunk else 0

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> PrefillTokenBudget:
		return cls(
			continues_chunk=_bool(buf[off + 0]),
		)


@_dc.dataclass
class BatchLaunched:
	TYPE_ID = 5
	FIXED_SIZE = 32

	batch_class: int = 0
	tokens: int = 0
	decode_rows: int = 0
	now: float = 0.0

	def encode(self) -> bytes:
		buf = bytearray(32)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: BatchLaunched: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> BatchLaunched:
		buf = _view(buf)
		if len(buf) < 32:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 32
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<B", buf, off + 0, self.batch_class)
		_st.pack_into("<q", buf, off + 8, self.tokens)
		_st.pack_into("<q", buf, off + 16, self.decode_rows)
		_st.pack_into("<d", buf, off + 24, self.now)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> BatchLaunched:
		return cls(
			batch_class=_st.unpack_from("<B", buf, off + 0)[0],
			tokens=_st.unpack_from("<q", buf, off + 8)[0],
			decode_rows=_st.unpack_from("<q", buf, off + 16)[0],
			now=_st.unpack_from("<d", buf, off + 24)[0],
		)


@_dc.dataclass
class BatchFinished:
	TYPE_ID = 6
	FIXED_SIZE = 8

	now: float = 0.0

	def encode(self) -> bytes:
		buf = bytearray(8)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: BatchFinished: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> BatchFinished:
		buf = _view(buf)
		if len(buf) < 8:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 8
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<d", buf, off + 0, self.now)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> BatchFinished:
		return cls(
			now=_st.unpack_from("<d", buf, off + 0)[0],
		)


@_dc.dataclass
class RequestQueued:
	TYPE_ID = 7
	FIXED_SIZE = 8

	now: float = 0.0
	rid: str = ""
	tokens: bytes = b""

	def encode(self) -> bytes:
		buf = bytearray(8)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: RequestQueued: %s" % e) from None
		_put_var(buf, self.rid.encode("utf-8"))
		_put_var(buf, bytes(self.tokens))
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> RequestQueued:
		buf = _view(buf)
		if len(buf) < 8:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 8
		raw, off = _get_var(buf, off)
		m.rid = _str(raw)
		raw, off = _get_var(buf, off)
		m.tokens = raw
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<d", buf, off + 0, self.now)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> RequestQueued:
		return cls(
			now=_st.unpack_from("<d", buf, off + 0)[0],
		)


@_dc.dataclass
class RequestFinished:
	TYPE_ID = 8
	FIXED_SIZE = 16

	now: float = 0.0
	length: int = 0
	rid: str = ""
	tail: bytes = b""

	def encode(self) -> bytes:
		buf = bytearray(16)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: RequestFinished: %s" % e) from None
		_put_var(buf, self.rid.encode("utf-8"))
		_put_var(buf, bytes(self.tail))
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> RequestFinished:
		buf = _view(buf)
		if len(buf) < 16:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 16
		raw, off = _get_var(buf, off)
		m.rid = _str(raw)
		raw, off = _get_var(buf, off)
		m.tail = raw
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<d", buf, off + 0, self.now)
		_st.pack_into("<q", buf, off + 8, self.length)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> RequestFinished:
		return cls(
			now=_st.unpack_from("<d", buf, off + 0)[0],
			length=_st.unpack_from("<q", buf, off + 8)[0],
		)


@_dc.dataclass
class BeginPass:
	TYPE_ID = 9
	FIXED_SIZE = 0

	present: str = ""

	def encode(self) -> bytes:
		buf = bytearray(0)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: BeginPass: %s" % e) from None
		_put_var(buf, self.present.encode("utf-8"))
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> BeginPass:
		buf = _view(buf)
		if len(buf) < 0:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 0
		raw, off = _get_var(buf, off)
		m.present = _str(raw)
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		pass

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> BeginPass:
		return cls()


@_dc.dataclass
class ShouldHold:
	TYPE_ID = 10
	FIXED_SIZE = 48

	input_len: int = 0
	device_hit: int = 0
	total_tokens: int = 0
	would_evict: bool = False
	queued_at: float = 0.0
	now: float = 0.0
	rid: str = ""

	def encode(self) -> bytes:
		buf = bytearray(48)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: ShouldHold: %s" % e) from None
		_put_var(buf, self.rid.encode("utf-8"))
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> ShouldHold:
		buf = _view(buf)
		if len(buf) < 48:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 48
		raw, off = _get_var(buf, off)
		m.rid = _str(raw)
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<q", buf, off + 0, self.input_len)
		_st.pack_into("<q", buf, off + 8, self.device_hit)
		_st.pack_into("<q", buf, off + 16, self.total_tokens)
		buf[off + 24] = 1 if self.would_evict else 0
		_st.pack_into("<d", buf, off + 32, self.queued_at)
		_st.pack_into("<d", buf, off + 40, self.now)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> ShouldHold:
		return cls(
			input_len=_st.unpack_from("<q", buf, off + 0)[0],
			device_hit=_st.unpack_from("<q", buf, off + 8)[0],
			total_tokens=_st.unpack_from("<q", buf, off + 16)[0],
			would_evict=_bool(buf[off + 24]),
			queued_at=_st.unpack_from("<d", buf, off + 32)[0],
			now=_st.unpack_from("<d", buf, off + 40)[0],
		)


@_dc.dataclass
class Admitted:
	TYPE_ID = 11
	FIXED_SIZE = 16

	evicted: bool = False
	now: float = 0.0

	def encode(self) -> bytes:
		buf = bytearray(16)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: Admitted: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> Admitted:
		buf = _view(buf)
		if len(buf) < 16:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 16
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		buf[off + 0] = 1 if self.evicted else 0
		_st.pack_into("<d", buf, off + 8, self.now)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> Admitted:
		return cls(
			evicted=_bool(buf[off + 0]),
			now=_st.unpack_from("<d", buf, off + 8)[0],
		)


@_dc.dataclass
class HelloOk:
	TYPE_ID = 100
	FIXED_SIZE = 4

	protocol: int = 0

	def encode(self) -> bytes:
		buf = bytearray(4)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: HelloOk: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> HelloOk:
		buf = _view(buf)
		if len(buf) < 4:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 4
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		_st.pack_into("<I", buf, off + 0, self.protocol)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> HelloOk:
		return cls(
			protocol=_st.unpack_from("<I", buf, off + 0)[0],
		)


@_dc.dataclass
class BoolReply:
	TYPE_ID = 101
	FIXED_SIZE = 1

	value: bool = False

	def encode(self) -> bytes:
		buf = bytearray(1)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: BoolReply: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> BoolReply:
		buf = _view(buf)
		if len(buf) < 1:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 1
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		buf[off + 0] = 1 if self.value else 0

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> BoolReply:
		return cls(
			value=_bool(buf[off + 0]),
		)


@_dc.dataclass
class OptIntReply:
	TYPE_ID = 102
	FIXED_SIZE = 16

	present: bool = False
	value: int = 0

	def encode(self) -> bytes:
		buf = bytearray(16)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: OptIntReply: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> OptIntReply:
		buf = _view(buf)
		if len(buf) < 16:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 16
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		buf[off + 0] = 1 if self.present else 0
		_st.pack_into("<q", buf, off + 8, self.value)

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> OptIntReply:
		return cls(
			present=_bool(buf[off + 0]),
			value=_st.unpack_from("<q", buf, off + 8)[0],
		)


@_dc.dataclass
class Ack:
	TYPE_ID = 103
	FIXED_SIZE = 0

	def encode(self) -> bytes:
		buf = bytearray(0)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: Ack: %s" % e) from None
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> Ack:
		buf = _view(buf)
		if len(buf) < 0:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 0
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		pass

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> Ack:
		return cls()


@_dc.dataclass
class Error:
	TYPE_ID = 255
	FIXED_SIZE = 0

	message: str = ""

	def encode(self) -> bytes:
		buf = bytearray(0)
		try:
			self._put(buf, 0)
		except (_st.error, OverflowError) as e:
			raise _Error("schedpolicy: Error: %s" % e) from None
		_put_var(buf, self.message.encode("utf-8"))
		return bytes(buf)

	@classmethod
	def decode(cls, buf: _t.Any) -> Error:
		buf = _view(buf)
		if len(buf) < 0:
			raise _Error("schedpolicy: input is shorter than the fixed section")
		m = cls._get(buf, 0)
		off = 0
		raw, off = _get_var(buf, off)
		m.message = _str(raw)
		if off != len(buf):
			raise _Error("schedpolicy: bytes remain after the last field")
		return m

	def _put(self, buf: bytearray, off: int) -> None:
		pass

	@classmethod
	def _get(cls, buf: memoryview, off: int) -> Error:
		return cls()


MESSAGES: _t.Dict[int, _t.Any] = {
	Hello.TYPE_ID: Hello,
	Init.TYPE_ID: Init,
	ShouldDeferPrefill.TYPE_ID: ShouldDeferPrefill,
	PrefillTokenBudget.TYPE_ID: PrefillTokenBudget,
	BatchLaunched.TYPE_ID: BatchLaunched,
	BatchFinished.TYPE_ID: BatchFinished,
	RequestQueued.TYPE_ID: RequestQueued,
	RequestFinished.TYPE_ID: RequestFinished,
	BeginPass.TYPE_ID: BeginPass,
	ShouldHold.TYPE_ID: ShouldHold,
	Admitted.TYPE_ID: Admitted,
	HelloOk.TYPE_ID: HelloOk,
	BoolReply.TYPE_ID: BoolReply,
	OptIntReply.TYPE_ID: OptIntReply,
	Ack.TYPE_ID: Ack,
	Error.TYPE_ID: Error,
}
