// Code generated by ipcgen. DO NOT EDIT.

// Package schedpolicy holds the messages of schema policy.ipc.
package schedpolicy

import (
	"encoding/binary"
	"errors"
	"math"
	"unicode/utf8"
)

var (
	errIpcgenShort    = errors.New("schedpolicy: input is shorter than the fixed section")
	errIpcgenLength   = errors.New("schedpolicy: a length runs past the end of the input")
	errIpcgenTrailing = errors.New("schedpolicy: bytes remain after the last field")
	errIpcgenBool     = errors.New("schedpolicy: a bool is neither 0 nor 1")
	errIpcgenUTF8     = errors.New("schedpolicy: a string is not valid UTF-8")
	errIpcgenTooLong  = errors.New("schedpolicy: a string or bytes field is longer than 4 GiB")
)

// ipcgenFits reports whether n fits in the u32 length prefix.
func ipcgenFits(n int) bool { return uint64(n) <= 0xFFFFFFFF }

// ipcgenPutVar writes a length prefix and v at off and returns the offset after them.
func ipcgenPutVar[T string | []byte](b []byte, off int, v T) int {
	binary.LittleEndian.PutUint32(b[off:], uint32(len(v)))
	return off + 4 + copy(b[off+4:], v)
}

// ipcgenGetVar reads a length prefix and the bytes after it.
func ipcgenGetVar(b []byte, off int) ([]byte, int, error) {
	if len(b)-off < 4 {
		return nil, 0, errIpcgenLength
	}
	n := binary.LittleEndian.Uint32(b[off:])
	off += 4
	if uint64(n) > uint64(len(b)-off) {
		return nil, 0, errIpcgenLength
	}
	return b[off : off+int(n)], off + int(n), nil
}

// Message is any message of package schedpolicy.
type Message interface {
	TypeID() uint32
	Size() int
	MarshalTo(b []byte) int
	MarshalBinary() ([]byte, error)
	UnmarshalBinary(b []byte) error
}

// NewMessage returns an empty message with the type ID, or nil for a type ID no message has.
func NewMessage(typeID uint32) Message {
	switch typeID {
	case HelloType:
		return &Hello{}
	case InitType:
		return &Init{}
	case ShouldDeferPrefillType:
		return &ShouldDeferPrefill{}
	case PrefillTokenBudgetType:
		return &PrefillTokenBudget{}
	case BatchLaunchedType:
		return &BatchLaunched{}
	case BatchFinishedType:
		return &BatchFinished{}
	case RequestQueuedType:
		return &RequestQueued{}
	case RequestFinishedType:
		return &RequestFinished{}
	case BeginPassType:
		return &BeginPass{}
	case ShouldHoldType:
		return &ShouldHold{}
	case AdmittedType:
		return &Admitted{}
	case HelloOkType:
		return &HelloOk{}
	case BoolReplyType:
		return &BoolReply{}
	case OptIntReplyType:
		return &OptIntReply{}
	case AckType:
		return &Ack{}
	}
	return nil
}

// Hello is message 1 of package schedpolicy.
type Hello struct {
	Protocol uint32
	Rank     uint32
	World    uint32
}

// HelloType is the type ID of Hello.
const HelloType uint32 = 1

// TypeID returns HelloType.
func (m *Hello) TypeID() uint32 { return HelloType }

// Size returns the encoded size of m.
func (m *Hello) Size() int {
	return 12
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *Hello) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *Hello) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *Hello) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:12])
	m.ipcgenPut(b)
	return 12, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *Hello) UnmarshalBinary(b []byte) error {
	if len(b) < 12 {
		return errIpcgenShort
	}
	var v Hello
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 12
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *Hello) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint32(b[0:], m.Protocol)
	binary.LittleEndian.PutUint32(b[4:], m.Rank)
	binary.LittleEndian.PutUint32(b[8:], m.World)
}

func (m *Hello) ipcgenGet(b []byte) error {
	m.Protocol = binary.LittleEndian.Uint32(b[0:])
	m.Rank = binary.LittleEndian.Uint32(b[4:])
	m.World = binary.LittleEndian.Uint32(b[8:])
	return nil
}

// Init is message 2 of package schedpolicy.
type Init struct {
	BurstTokens  int64
	DeviceTokens int64
	HostTokens   int64
	Throttle     bool
}

// InitType is the type ID of Init.
const InitType uint32 = 2

// TypeID returns InitType.
func (m *Init) TypeID() uint32 { return InitType }

// Size returns the encoded size of m.
func (m *Init) Size() int {
	return 32
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *Init) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *Init) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *Init) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:32])
	m.ipcgenPut(b)
	return 32, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *Init) UnmarshalBinary(b []byte) error {
	if len(b) < 32 {
		return errIpcgenShort
	}
	var v Init
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 32
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *Init) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint64(b[0:], uint64(m.BurstTokens))
	binary.LittleEndian.PutUint64(b[8:], uint64(m.DeviceTokens))
	binary.LittleEndian.PutUint64(b[16:], uint64(m.HostTokens))
	if m.Throttle {
		b[24] = 1
	}
}

func (m *Init) ipcgenGet(b []byte) error {
	m.BurstTokens = int64(binary.LittleEndian.Uint64(b[0:]))
	m.DeviceTokens = int64(binary.LittleEndian.Uint64(b[8:]))
	m.HostTokens = int64(binary.LittleEndian.Uint64(b[16:]))
	if b[24] > 1 {
		return errIpcgenBool
	}
	m.Throttle = b[24] == 1
	return nil
}

// ShouldDeferPrefill is message 3 of package schedpolicy.
type ShouldDeferPrefill struct {
	PrefillPending bool
	DecodeRunnable bool
	ContinuesChunk bool
}

// ShouldDeferPrefillType is the type ID of ShouldDeferPrefill.
const ShouldDeferPrefillType uint32 = 3

// TypeID returns ShouldDeferPrefillType.
func (m *ShouldDeferPrefill) TypeID() uint32 { return ShouldDeferPrefillType }

// Size returns the encoded size of m.
func (m *ShouldDeferPrefill) Size() int {
	return 3
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *ShouldDeferPrefill) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *ShouldDeferPrefill) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *ShouldDeferPrefill) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:3])
	m.ipcgenPut(b)
	return 3, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *ShouldDeferPrefill) UnmarshalBinary(b []byte) error {
	if len(b) < 3 {
		return errIpcgenShort
	}
	var v ShouldDeferPrefill
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 3
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *ShouldDeferPrefill) ipcgenPut(b []byte) {
	if m.PrefillPending {
		b[0] = 1
	}
	if m.DecodeRunnable {
		b[1] = 1
	}
	if m.ContinuesChunk {
		b[2] = 1
	}
}

func (m *ShouldDeferPrefill) ipcgenGet(b []byte) error {
	if b[0] > 1 {
		return errIpcgenBool
	}
	m.PrefillPending = b[0] == 1
	if b[1] > 1 {
		return errIpcgenBool
	}
	m.DecodeRunnable = b[1] == 1
	if b[2] > 1 {
		return errIpcgenBool
	}
	m.ContinuesChunk = b[2] == 1
	return nil
}

// PrefillTokenBudget is message 4 of package schedpolicy.
type PrefillTokenBudget struct {
	ContinuesChunk bool
}

// PrefillTokenBudgetType is the type ID of PrefillTokenBudget.
const PrefillTokenBudgetType uint32 = 4

// TypeID returns PrefillTokenBudgetType.
func (m *PrefillTokenBudget) TypeID() uint32 { return PrefillTokenBudgetType }

// Size returns the encoded size of m.
func (m *PrefillTokenBudget) Size() int {
	return 1
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *PrefillTokenBudget) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *PrefillTokenBudget) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *PrefillTokenBudget) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:1])
	m.ipcgenPut(b)
	return 1, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *PrefillTokenBudget) UnmarshalBinary(b []byte) error {
	if len(b) < 1 {
		return errIpcgenShort
	}
	var v PrefillTokenBudget
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 1
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *PrefillTokenBudget) ipcgenPut(b []byte) {
	if m.ContinuesChunk {
		b[0] = 1
	}
}

func (m *PrefillTokenBudget) ipcgenGet(b []byte) error {
	if b[0] > 1 {
		return errIpcgenBool
	}
	m.ContinuesChunk = b[0] == 1
	return nil
}

// BatchLaunched is message 5 of package schedpolicy.
type BatchLaunched struct {
	BatchClass uint8
	Tokens     int64
	DecodeRows int64
	Now        float64
}

// BatchLaunchedType is the type ID of BatchLaunched.
const BatchLaunchedType uint32 = 5

// TypeID returns BatchLaunchedType.
func (m *BatchLaunched) TypeID() uint32 { return BatchLaunchedType }

// Size returns the encoded size of m.
func (m *BatchLaunched) Size() int {
	return 32
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *BatchLaunched) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *BatchLaunched) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *BatchLaunched) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:32])
	m.ipcgenPut(b)
	return 32, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *BatchLaunched) UnmarshalBinary(b []byte) error {
	if len(b) < 32 {
		return errIpcgenShort
	}
	var v BatchLaunched
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 32
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *BatchLaunched) ipcgenPut(b []byte) {
	b[0] = byte(m.BatchClass)
	binary.LittleEndian.PutUint64(b[8:], uint64(m.Tokens))
	binary.LittleEndian.PutUint64(b[16:], uint64(m.DecodeRows))
	binary.LittleEndian.PutUint64(b[24:], math.Float64bits(m.Now))
}

func (m *BatchLaunched) ipcgenGet(b []byte) error {
	m.BatchClass = uint8(b[0])
	m.Tokens = int64(binary.LittleEndian.Uint64(b[8:]))
	m.DecodeRows = int64(binary.LittleEndian.Uint64(b[16:]))
	m.Now = math.Float64frombits(binary.LittleEndian.Uint64(b[24:]))
	return nil
}

// BatchFinished is message 6 of package schedpolicy.
type BatchFinished struct {
	Now float64
}

// BatchFinishedType is the type ID of BatchFinished.
const BatchFinishedType uint32 = 6

// TypeID returns BatchFinishedType.
func (m *BatchFinished) TypeID() uint32 { return BatchFinishedType }

// Size returns the encoded size of m.
func (m *BatchFinished) Size() int {
	return 8
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *BatchFinished) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *BatchFinished) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *BatchFinished) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:8])
	m.ipcgenPut(b)
	return 8, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *BatchFinished) UnmarshalBinary(b []byte) error {
	if len(b) < 8 {
		return errIpcgenShort
	}
	var v BatchFinished
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 8
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *BatchFinished) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint64(b[0:], math.Float64bits(m.Now))
}

func (m *BatchFinished) ipcgenGet(b []byte) error {
	m.Now = math.Float64frombits(binary.LittleEndian.Uint64(b[0:]))
	return nil
}

// RequestQueued is message 7 of package schedpolicy.
type RequestQueued struct {
	Now    float64
	Rid    string
	Tokens []byte
}

// RequestQueuedType is the type ID of RequestQueued.
const RequestQueuedType uint32 = 7

// TypeID returns RequestQueuedType.
func (m *RequestQueued) TypeID() uint32 { return RequestQueuedType }

// Size returns the encoded size of m.
func (m *RequestQueued) Size() int {
	return 8 + 4 + len(m.Rid) + 4 + len(m.Tokens)
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *RequestQueued) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *RequestQueued) MarshalBinary() ([]byte, error) {
	if !ipcgenFits(len(m.Rid)) || !ipcgenFits(len(m.Tokens)) {
		return nil, errIpcgenTooLong
	}
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *RequestQueued) ipcgenMarshal(b []byte) (int, bool) {
	if !ipcgenFits(len(m.Rid)) || !ipcgenFits(len(m.Tokens)) {
		return 0, false
	}
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:8])
	m.ipcgenPut(b)
	off := 8
	off = ipcgenPutVar(b, off, m.Rid)
	off = ipcgenPutVar(b, off, m.Tokens)
	return off, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *RequestQueued) UnmarshalBinary(b []byte) error {
	if len(b) < 8 {
		return errIpcgenShort
	}
	var v RequestQueued
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 8
	var raw []byte
	var err error
	if raw, off, err = ipcgenGetVar(b, off); err != nil {
		return err
	}
	if !utf8.Valid(raw) {
		return errIpcgenUTF8
	}
	v.Rid = string(raw)
	if raw, off, err = ipcgenGetVar(b, off); err != nil {
		return err
	}
	v.Tokens = append([]byte{}, raw...)
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *RequestQueued) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint64(b[0:], math.Float64bits(m.Now))
}

func (m *RequestQueued) ipcgenGet(b []byte) error {
	m.Now = math.Float64frombits(binary.LittleEndian.Uint64(b[0:]))
	return nil
}

// RequestFinished is message 8 of package schedpolicy.
type RequestFinished struct {
	Now    float64
	Length int64
	Rid    string
	Tail   []byte
}

// RequestFinishedType is the type ID of RequestFinished.
const RequestFinishedType uint32 = 8

// TypeID returns RequestFinishedType.
func (m *RequestFinished) TypeID() uint32 { return RequestFinishedType }

// Size returns the encoded size of m.
func (m *RequestFinished) Size() int {
	return 16 + 4 + len(m.Rid) + 4 + len(m.Tail)
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *RequestFinished) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *RequestFinished) MarshalBinary() ([]byte, error) {
	if !ipcgenFits(len(m.Rid)) || !ipcgenFits(len(m.Tail)) {
		return nil, errIpcgenTooLong
	}
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *RequestFinished) ipcgenMarshal(b []byte) (int, bool) {
	if !ipcgenFits(len(m.Rid)) || !ipcgenFits(len(m.Tail)) {
		return 0, false
	}
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:16])
	m.ipcgenPut(b)
	off := 16
	off = ipcgenPutVar(b, off, m.Rid)
	off = ipcgenPutVar(b, off, m.Tail)
	return off, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *RequestFinished) UnmarshalBinary(b []byte) error {
	if len(b) < 16 {
		return errIpcgenShort
	}
	var v RequestFinished
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 16
	var raw []byte
	var err error
	if raw, off, err = ipcgenGetVar(b, off); err != nil {
		return err
	}
	if !utf8.Valid(raw) {
		return errIpcgenUTF8
	}
	v.Rid = string(raw)
	if raw, off, err = ipcgenGetVar(b, off); err != nil {
		return err
	}
	v.Tail = append([]byte{}, raw...)
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *RequestFinished) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint64(b[0:], math.Float64bits(m.Now))
	binary.LittleEndian.PutUint64(b[8:], uint64(m.Length))
}

func (m *RequestFinished) ipcgenGet(b []byte) error {
	m.Now = math.Float64frombits(binary.LittleEndian.Uint64(b[0:]))
	m.Length = int64(binary.LittleEndian.Uint64(b[8:]))
	return nil
}

// BeginPass is message 9 of package schedpolicy.
type BeginPass struct {
	Present string
}

// BeginPassType is the type ID of BeginPass.
const BeginPassType uint32 = 9

// TypeID returns BeginPassType.
func (m *BeginPass) TypeID() uint32 { return BeginPassType }

// Size returns the encoded size of m.
func (m *BeginPass) Size() int {
	return 0 + 4 + len(m.Present)
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *BeginPass) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *BeginPass) MarshalBinary() ([]byte, error) {
	if !ipcgenFits(len(m.Present)) {
		return nil, errIpcgenTooLong
	}
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *BeginPass) ipcgenMarshal(b []byte) (int, bool) {
	if !ipcgenFits(len(m.Present)) {
		return 0, false
	}
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:0])
	m.ipcgenPut(b)
	off := 0
	off = ipcgenPutVar(b, off, m.Present)
	return off, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *BeginPass) UnmarshalBinary(b []byte) error {
	if len(b) < 0 {
		return errIpcgenShort
	}
	var v BeginPass
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 0
	var raw []byte
	var err error
	if raw, off, err = ipcgenGetVar(b, off); err != nil {
		return err
	}
	if !utf8.Valid(raw) {
		return errIpcgenUTF8
	}
	v.Present = string(raw)
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *BeginPass) ipcgenPut(b []byte) {
}

func (m *BeginPass) ipcgenGet(b []byte) error {
	return nil
}

// ShouldHold is message 10 of package schedpolicy.
type ShouldHold struct {
	InputLen    int64
	DeviceHit   int64
	TotalTokens int64
	WouldEvict  bool
	QueuedAt    float64
	Now         float64
	Rid         string
}

// ShouldHoldType is the type ID of ShouldHold.
const ShouldHoldType uint32 = 10

// TypeID returns ShouldHoldType.
func (m *ShouldHold) TypeID() uint32 { return ShouldHoldType }

// Size returns the encoded size of m.
func (m *ShouldHold) Size() int {
	return 48 + 4 + len(m.Rid)
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *ShouldHold) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *ShouldHold) MarshalBinary() ([]byte, error) {
	if !ipcgenFits(len(m.Rid)) {
		return nil, errIpcgenTooLong
	}
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *ShouldHold) ipcgenMarshal(b []byte) (int, bool) {
	if !ipcgenFits(len(m.Rid)) {
		return 0, false
	}
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:48])
	m.ipcgenPut(b)
	off := 48
	off = ipcgenPutVar(b, off, m.Rid)
	return off, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *ShouldHold) UnmarshalBinary(b []byte) error {
	if len(b) < 48 {
		return errIpcgenShort
	}
	var v ShouldHold
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 48
	var raw []byte
	var err error
	if raw, off, err = ipcgenGetVar(b, off); err != nil {
		return err
	}
	if !utf8.Valid(raw) {
		return errIpcgenUTF8
	}
	v.Rid = string(raw)
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *ShouldHold) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint64(b[0:], uint64(m.InputLen))
	binary.LittleEndian.PutUint64(b[8:], uint64(m.DeviceHit))
	binary.LittleEndian.PutUint64(b[16:], uint64(m.TotalTokens))
	if m.WouldEvict {
		b[24] = 1
	}
	binary.LittleEndian.PutUint64(b[32:], math.Float64bits(m.QueuedAt))
	binary.LittleEndian.PutUint64(b[40:], math.Float64bits(m.Now))
}

func (m *ShouldHold) ipcgenGet(b []byte) error {
	m.InputLen = int64(binary.LittleEndian.Uint64(b[0:]))
	m.DeviceHit = int64(binary.LittleEndian.Uint64(b[8:]))
	m.TotalTokens = int64(binary.LittleEndian.Uint64(b[16:]))
	if b[24] > 1 {
		return errIpcgenBool
	}
	m.WouldEvict = b[24] == 1
	m.QueuedAt = math.Float64frombits(binary.LittleEndian.Uint64(b[32:]))
	m.Now = math.Float64frombits(binary.LittleEndian.Uint64(b[40:]))
	return nil
}

// Admitted is message 11 of package schedpolicy.
type Admitted struct {
	Evicted bool
	Now     float64
}

// AdmittedType is the type ID of Admitted.
const AdmittedType uint32 = 11

// TypeID returns AdmittedType.
func (m *Admitted) TypeID() uint32 { return AdmittedType }

// Size returns the encoded size of m.
func (m *Admitted) Size() int {
	return 16
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *Admitted) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *Admitted) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *Admitted) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:16])
	m.ipcgenPut(b)
	return 16, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *Admitted) UnmarshalBinary(b []byte) error {
	if len(b) < 16 {
		return errIpcgenShort
	}
	var v Admitted
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 16
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *Admitted) ipcgenPut(b []byte) {
	if m.Evicted {
		b[0] = 1
	}
	binary.LittleEndian.PutUint64(b[8:], math.Float64bits(m.Now))
}

func (m *Admitted) ipcgenGet(b []byte) error {
	if b[0] > 1 {
		return errIpcgenBool
	}
	m.Evicted = b[0] == 1
	m.Now = math.Float64frombits(binary.LittleEndian.Uint64(b[8:]))
	return nil
}

// HelloOk is message 100 of package schedpolicy.
type HelloOk struct {
	Protocol uint32
}

// HelloOkType is the type ID of HelloOk.
const HelloOkType uint32 = 100

// TypeID returns HelloOkType.
func (m *HelloOk) TypeID() uint32 { return HelloOkType }

// Size returns the encoded size of m.
func (m *HelloOk) Size() int {
	return 4
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *HelloOk) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *HelloOk) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *HelloOk) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:4])
	m.ipcgenPut(b)
	return 4, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *HelloOk) UnmarshalBinary(b []byte) error {
	if len(b) < 4 {
		return errIpcgenShort
	}
	var v HelloOk
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 4
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *HelloOk) ipcgenPut(b []byte) {
	binary.LittleEndian.PutUint32(b[0:], m.Protocol)
}

func (m *HelloOk) ipcgenGet(b []byte) error {
	m.Protocol = binary.LittleEndian.Uint32(b[0:])
	return nil
}

// BoolReply is message 101 of package schedpolicy.
type BoolReply struct {
	Value bool
}

// BoolReplyType is the type ID of BoolReply.
const BoolReplyType uint32 = 101

// TypeID returns BoolReplyType.
func (m *BoolReply) TypeID() uint32 { return BoolReplyType }

// Size returns the encoded size of m.
func (m *BoolReply) Size() int {
	return 1
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *BoolReply) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *BoolReply) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *BoolReply) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:1])
	m.ipcgenPut(b)
	return 1, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *BoolReply) UnmarshalBinary(b []byte) error {
	if len(b) < 1 {
		return errIpcgenShort
	}
	var v BoolReply
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 1
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *BoolReply) ipcgenPut(b []byte) {
	if m.Value {
		b[0] = 1
	}
}

func (m *BoolReply) ipcgenGet(b []byte) error {
	if b[0] > 1 {
		return errIpcgenBool
	}
	m.Value = b[0] == 1
	return nil
}

// OptIntReply is message 102 of package schedpolicy.
type OptIntReply struct {
	Present bool
	Value   int64
}

// OptIntReplyType is the type ID of OptIntReply.
const OptIntReplyType uint32 = 102

// TypeID returns OptIntReplyType.
func (m *OptIntReply) TypeID() uint32 { return OptIntReplyType }

// Size returns the encoded size of m.
func (m *OptIntReply) Size() int {
	return 16
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *OptIntReply) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *OptIntReply) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *OptIntReply) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:16])
	m.ipcgenPut(b)
	return 16, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *OptIntReply) UnmarshalBinary(b []byte) error {
	if len(b) < 16 {
		return errIpcgenShort
	}
	var v OptIntReply
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 16
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *OptIntReply) ipcgenPut(b []byte) {
	if m.Present {
		b[0] = 1
	}
	binary.LittleEndian.PutUint64(b[8:], uint64(m.Value))
}

func (m *OptIntReply) ipcgenGet(b []byte) error {
	if b[0] > 1 {
		return errIpcgenBool
	}
	m.Present = b[0] == 1
	m.Value = int64(binary.LittleEndian.Uint64(b[8:]))
	return nil
}

// Ack is message 103 of package schedpolicy.
type Ack struct {
}

// AckType is the type ID of Ack.
const AckType uint32 = 103

// TypeID returns AckType.
func (m *Ack) TypeID() uint32 { return AckType }

// Size returns the encoded size of m.
func (m *Ack) Size() int {
	return 0
}

// MarshalTo encodes m into b and returns the bytes written.
// It returns 0 when b is shorter than Size or a string or bytes field is longer than 4 GiB.
func (m *Ack) MarshalTo(b []byte) int {
	n, _ := m.ipcgenMarshal(b)
	return n
}

// MarshalBinary returns the encoding of m.
func (m *Ack) MarshalBinary() ([]byte, error) {
	b := make([]byte, m.Size())
	m.ipcgenMarshal(b)
	return b, nil
}

func (m *Ack) ipcgenMarshal(b []byte) (int, bool) {
	if len(b) < m.Size() {
		return 0, false
	}
	clear(b[:0])
	m.ipcgenPut(b)
	return 0, true
}

// UnmarshalBinary decodes b into m. It leaves m unchanged when b is malformed.
func (m *Ack) UnmarshalBinary(b []byte) error {
	if len(b) < 0 {
		return errIpcgenShort
	}
	var v Ack
	if err := v.ipcgenGet(b); err != nil {
		return err
	}
	off := 0
	if off != len(b) {
		return errIpcgenTrailing
	}
	*m = v
	return nil
}

func (m *Ack) ipcgenPut(b []byte) {
}

func (m *Ack) ipcgenGet(b []byte) error {
	return nil
}
